<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="SpaceX_Launch_Website._Default" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %> 


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head runat="server">
        <title></title>
    </head>
    <body>
        <form id="form1" runat="server">
            <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
                <Scripts>
                    <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js" />
                    <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js" />
                    <asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js" />
                </Scripts>
            </telerik:RadScriptManager>

            <telerik:RadGrid ID="RadGrid1" Skin="Bootstrap" AllowAutomaticDeletes="True" AllowAutomaticInserts="true" AutoGenerateDeleteColumn="True" AllowAutomaticUpdates="True" AllowFilteringByColumn="True" AllowMultiRowSelection="True" runat="server" CellSpacing="-1" GridLines="Both" OnNeedDataSource="RadGrid1_NeedDataSource">
                <MasterTableView AutoGenerateColumns="false" DataKeyNames="LaunchID">
                    <SortExpressions>
                        <telerik:GridSortExpression FieldName="Date" SortOrder="Descending" />
                    </SortExpressions>
                    <Columns>
                        <telerik:GridBoundColumn DataField="LaunchID" HeaderText="LaunchID" SortExpression="LaunchID" UniqueName="LaunchID"></telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="Date" HeaderText="Date" SortExpression="Date" UniqueName="Date"></telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="RocketName" HeaderText="RocketName" SortExpression="Name" UniqueName="Name"></telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="Success" HeaderText="Success" SortExpression="Success" UniqueName="Success"></telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="PayloadMass" HeaderText="Payload" SortExpression="Payload" UniqueName="Payload"></telerik:GridBoundColumn>
                        <telerik:GridBoundColumn DataField="PayloadRank" HeaderText="Payload Rank" SortExpression="PayloadRank" UniqueName="PayloadRank"></telerik:GridBoundColumn>
                    </Columns>
                </MasterTableView>
            </telerik:RadGrid>
        </form>
    </body>
</html>
